// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SendChat2(arg1) {
  return window['go']['main']['App']['SendChat2'](arg1);
}
