// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetConfig():Promise<model.ConfigJson>;

export function GetModels():Promise<string>;

export function GetOllamaModels(arg1:string):Promise<string>;

export function SendChat(arg1:string,arg2:string,arg3:Array<model.Chat>):Promise<string>;

export function UpdateAppTheme(arg1:string):Promise<string>;

export function UpdateOllamaEndpoints(arg1:Array<model.OllamaEndpoint>):Promise<string>;
