// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetConfig():Promise<model.ConfigJson>;

export function SendChat(arg1:string,arg2:string,arg3:Array<model.Chat>):Promise<string>;
