// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SendChat(arg1:string):Promise<string>;

export function SendChat2(arg1:Array<main.Chat>):Promise<string>;
